---
- name: Playbook setup docker
  hosts: "{{ variable_host | default('fedora') }}"
  become: true
  gather_facts: false
  tasks:
    - name: Remove old Docker versions
      ansible.builtin.dnf:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-selinux
          - docker-engine-selinux
          - docker-engine
        state: absent

    - name: Install required system packages
      ansible.builtin.dnf:
        name:
          - curl
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install dnf-plugins-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: latest
        update_cache: true

    - name: Add Docker Repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Add "fedora" user to "docker" group
      remote_user: "{{ variable_user | default('fedora') }}"
      ansible.builtin.user:
        name: "{{ variable_user | default('fedora') }}"
        groups: docker
        append: true
      tags:
        - docker
